#define PAD_KEY_LEFT 1
#define PAD_KEY_DOWN 2
#define PAD_KEY_RIGHT 3
#define PAD_KEY_UP 4
#define PAD_KEY_START 5
#define PAD_KEY_R_JOYSTICK 5
#define PAD_KEY_L_JOYSTICK 6
#define PAD_KEY_SELECT 7
#define PAD_KEY_SHIKAKU 8
#define PAD_KEY_BATSU 9
#define PAD_KEY_MARU 10
#define PAD_KEY_SANKAKU 11
#define PAD_KEY_R1 12
#define PAD_KEY_L1 13
#define PAD_KEY_R2 14
#define PAD_KEY_L2 15

#define PAD_LEFT_X 1
#define PAD_LEFT_Y 2
#define PAD_RIGHT_X 3
#define PAD_RIGHT_Y 4
#define PAD_RIGHT 5
#define PAD_LEFT 6
#define PAD_UP 7
#define PAD_DOWN 8
#define PAD_SANKAKU 9
#define PAD_MARU 10
#define PAD_BATSU 11
#define PAD_SHIKAKU 12
#define PAD_L1 13
#define PAD_R1 14
#define PAD_L2 15
#define PAD_R2 16
